# Generated by Django 4.1.1 on 2022-10-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cat_field',
            field=models.TextField(),
        ),
    ]
